version: '3'

services:
    mysql-development:
        image: mysql:5.7
        container_name: mysql_dev
        environment:
            MYSQL_ROOT_PASSWORD: rootpasswd
            MYSQL_DATABASE: db_customers
        ports:
            - "3306:3306"
        volumes:
            - ./scripts/createDatabase.sql:/docker-entrypoint-initdb.d/createDatabase.sql